# Generated by Django 5.2.6 on 2025-09-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_category_options_remove_ad_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.CharField(default='Bakı', max_length=100),
        ),
        migrations.AddField(
            model_name='ad',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
    ]
