# Generated by Django 5.2.6 on 2025-09-07 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_city_ad_delivery_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='delivery',
            new_name='is_delivery',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_images/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.category'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='AdImage',
        ),
    ]
