# Generated by Django 5.2.6 on 2025-09-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_rename_delivery_ad_is_delivery_remove_ad_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='ads.category'),
        ),
    ]
