# Generated by Django 5.2.6 on 2025-09-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_remove_ad_image_adimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ad_type',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='is_delivery',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='email',
            field=models.EmailField(default='example@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(default='Bakı', max_length=100),
        ),
        migrations.AddField(
            model_name='ad',
            name='phone_number',
            field=models.CharField(default='050-000-00-00', max_length=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ads.category'),
            preserve_default=False,
        ),
    ]
