# Generated by Django 5.2.6 on 2025-09-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_remove_ad_ad_type_remove_ad_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ad_image',
        ),
    ]
