# Generated by Django 5.2.6 on 2025-09-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_ad_is_premium_premiumrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='premium_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
