# Generated by Django 5.2.6 on 2025-09-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_ad_premium_date_ad_premium_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video linki'),
        ),
    ]
